# .github/workflows/tagpr.yml
name: Tagpr
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
